# Generated by Django 4.0.3 on 2022-04-02 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='filmwork',
            name='file_path',
        ),
    ]
